#+TITLE: ResignXcode
#+AUTHOR: slegetank
#+OPTIONS: \n:\n

This little script's purpose is resign Xcode with a self-signed certificate.
From Xcode8, apple stops the support of third-party plugins to give programmers more security. This is really inconvenience for me. Everytime Xcode updates, I have to resign Xcode mannually to continue the use of XVim[[https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md][(Manual From XVim)]]. So, before the widely use of Xcode officially extensions, I'll have to use this to help me.
* Use 
#+BEGIN_SRC python
python ResignXcode.py
#+END_SRC
* You should know
1. If you don't know what's going on with this script, then don't use it, because it'll put you under risk.
2. You can read the code to decide if you want to use it.
* Simple explain 
Here's what the code does:

1. Use openssl to generate 2048 RSA self-signed certificate.
2. Import the cer into your keychain.
3. Resign your Xcode.
* Other things
+ Another good app to use: https://github.com/fpg1503/MakeXcodeGr8Again#should-i-use-it
+ A discuss: https://github.com/alcatraz/Alcatraz/issues/475
+ Openssl req configuration file format: https://wiki.openssl.org/index.php/Manual:Req(1)
+ Generate right self-signed cer: http://security.stackexchange.com/questions/17909/how-to-create-an-apple-installer-package-signing-certificate?answertab=votes#tab-top
